<a href="https://colab.research.google.com/github/anazzmuhmad/casestudy_numpypandas_anaz/blob/main/activity_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np
filepath='https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/master/IMDB-Movie-Data.csv'
df=pd.read_csv(filepath)
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [7]:
#shape
df.shape

(1000, 12)

In [8]:
#head
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [9]:
#column names
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [10]:
#data types
df.dtypes

Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

In [12]:
#missing values
df.isnull().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

In [13]:
#check duplicates
df.duplicated().sum()

np.int64(0)

In [16]:
#remove duplicates
df=df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [33]:
#rename columns
df.rename(columns={"Title":"Movie_Title"},inplace=True)
df.columns

Index(['Rank', 'Movie_Title', 'Genre', 'Description', 'Director', 'Actors',
       'Year', 'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [37]:
#unique genres
df["Genre"].unique()

array(['Action,Adventure,Sci-Fi', 'Adventure,Mystery,Sci-Fi',
       'Horror,Thriller', 'Animation,Comedy,Family',
       'Action,Adventure,Fantasy', 'Comedy,Drama,Music', 'Comedy',
       'Action,Adventure,Biography', 'Adventure,Drama,Romance',
       'Adventure,Family,Fantasy', 'Biography,Drama,History',
       'Animation,Adventure,Comedy', 'Action,Comedy,Drama',
       'Action,Thriller', 'Biography,Drama', 'Drama,Mystery,Sci-Fi',
       'Adventure,Drama,Thriller', 'Drama', 'Crime,Drama,Horror',
       'Action,Adventure,Drama', 'Drama,Thriller',
       'Action,Adventure,Comedy', 'Action,Horror,Sci-Fi',
       'Adventure,Drama,Sci-Fi', 'Action,Adventure,Western',
       'Comedy,Drama', 'Horror', 'Adventure,Drama,Fantasy',
       'Action,Crime,Thriller', 'Action,Crime,Drama',
       'Adventure,Drama,History', 'Crime,Horror,Thriller',
       'Drama,Romance', 'Comedy,Drama,Romance', 'Horror,Mystery,Thriller',
       'Crime,Drama,Mystery', 'Drama,Romance,Thriller',
       'Drama,History,Thriller', 'Action,Drama,Thriller', 'Drama,History',
       'Action,Drama,Romance', 'Drama,Fantasy', 'Action,Sci-Fi',
       'Adventure,Drama,War', 'Action,Comedy,Fantasy',
       'Biography,Comedy,Crime', 'Crime,Drama', 'Comedy,Crime,Drama',
       'Action,Comedy,Crime', 'Animation,Drama,Fantasy',
       'Horror,Mystery,Sci-Fi', 'Drama,Mystery,Thriller',
       'Crime,Drama,Thriller', 'Biography,Crime,Drama',
       'Crime,Mystery,Thriller', 'Action,Horror,Thriller',
       'Romance,Sci-Fi', 'Action,Fantasy,War', 'Action,Biography,Drama',
       'Drama,Horror,Mystery', 'Adventure,Drama,Family',
       'Adventure,Comedy,Romance', 'Action', 'Adventure,Crime,Mystery',
       'Comedy,Family,Musical', 'Adventure,Comedy,Drama',
       'Drama,Horror,Thriller', 'Drama,Music', 'Mystery,Thriller',
       'Mystery,Thriller,Western', 'Comedy,Family',
       'Biography,Comedy,Drama', 'Drama,Western', 'Drama,Mystery,Romance',
       'Action,Drama,Mystery', 'Action,Adventure,Crime',
       'Adventure,Sci-Fi,Thriller', 'Action,Comedy,Mystery',
       'Thriller,War', 'Action,Adventure,Thriller',
       'Drama,Fantasy,Romance', 'Action,Drama,History',
       'Animation,Adventure,Family', 'Adventure,Horror',
       'Drama,Romance,Sci-Fi', 'Action,Adventure,Family', 'Action,Comedy',
       'Comedy,Romance', 'Horror,Mystery', 'Drama,Family,Fantasy',
       'Sci-Fi', 'Drama,War', 'Drama,Fantasy,Horror',
       'Crime,Drama,History', 'Horror,Sci-Fi,Thriller',
       'Action,Drama,Sport', 'Adventure,Biography,Drama',
       'Biography,Drama,Thriller', 'Action,Adventure,Mystery',
       'Drama,Horror', 'Comedy,Crime', 'Drama,Fantasy,War',
       'Action,Adventure,Romance', 'Action,Drama,War',
       'Drama,Musical,Romance', 'Drama,Sci-Fi,Thriller',
       'Action,Drama,Sci-Fi', 'Drama,Sci-Fi', 'Adventure,Fantasy',
       'Thriller', 'Biography,Drama,Romance', 'Action,Adventure',
       'Action,Fantasy', 'Action,Drama,Horror', 'Comedy,Music,Romance',
       'Biography,Drama,Sport', 'Action,Horror', 'Comedy,Horror,Thriller',
       'Crime,Drama,Music', 'Action,Sci-Fi,Thriller',
       'Drama,Horror,Sci-Fi', 'Drama,Sport', 'Comedy,Horror',
       'Comedy,Fantasy,Romance', 'Comedy,Fantasy', 'Comedy,Drama,Fantasy',
       'Adventure,Comedy,Horror', 'Comedy,Mystery',
       'Action,Mystery,Sci-Fi', 'Action,Crime,Fantasy',
       'Comedy,Fantasy,Horror', 'Animation,Action,Adventure',
       'Action,Comedy,Family', 'Comedy,Sci-Fi', 'Action,Biography,Crime',
       'Adventure,Comedy', 'Comedy,Music', 'Comedy,Drama,Horror',
       'Action,Horror,Romance', 'Action,Drama,Fantasy',
       'Action,Mystery,Thriller', 'Action,Adventure,Horror',
       'Animation,Family,Fantasy', 'Adventure,Horror,Mystery',
       'Action,Horror,Mystery', 'Adventure,Comedy,Family',
       'Action,Crime,Mystery', 'Comedy,Drama,Family',
       'Action,Crime,Sport', 'Mystery,Sci-Fi,Thriller', 'Sci-Fi,Thriller',
       'Adventure,Drama,Horror', 'Biography,History,Thriller',
       'Adventure,Comedy,Sci-Fi', 'Fantasy,Horror',
       'Action,Fantasy,Thriller', 'Comedy,Romance,Sport',
       'Animation,Action,Comedy', 'Drama,Fantasy,Thriller',
       'Action,Comedy,Romance', 'Action,Fantasy,Horror',
       'Mystery,Romance,Sci-Fi', 'Comedy,Drama,Thriller',
       'Comedy,Western', 'Drama,History,War', 'Fantasy,Horror,Thriller',
       'Drama,Horror,Musical', 'Drama,Family', 'Romance,Sci-Fi,Thriller',
       'Animation,Fantasy', 'Drama,Mystery,War', 'Action,Drama,Family',
       'Adventure,Drama,Western', 'Drama,Music,Romance',
       'Comedy,Romance,Western', 'Adventure,Drama', 'Drama,Thriller,War',
       'Drama,Fantasy,Mystery', 'Comedy,Crime,Thriller',
       'Animation,Comedy,Drama', 'Action,Comedy,Sci-Fi',
       'Drama,Romance,War', 'Adventure,Fantasy,Mystery',
       'Mystery,Romance,Thriller', 'Biography,Drama,Mystery',
       'Animation,Drama,Romance', 'Comedy,Horror,Romance',
       'Action,Thriller,War', 'Action,Comedy,Horror',
       'Action,Crime,Sci-Fi', 'Crime,Thriller', 'Comedy,Horror,Sci-Fi',
       'Crime,Drama,Fantasy', 'Drama,Fantasy,Music',
       'Action,Comedy,Sport', 'Fantasy,Mystery,Thriller', 'Adventure',
       'Adventure,Biography', 'Adventure,Biography,Crime',
       'Comedy,Drama,Musical', 'Comedy,Family,Romance',
       'Biography,Drama,Family', 'Drama,Fantasy,Musical',
       'Adventure,Family', 'Adventure,Comedy,Fantasy',
       'Drama,Family,Music', 'Comedy,Family,Fantasy'], dtype=object)

In [43]:
#number of genres
def count_genres(genres):
    return len(genres.split(","))
df["Genre_Count"] = df["Genre"].apply(count_genres)
df[["Movie_Title", "Genre_Count"]]

                 Movie_Title  Genre_Count
0    Guardians of the Galaxy            3
1                 Prometheus            3
2                      Split            2
3                       Sing            3
4              Suicide Squad            3
..                       ...          ...
995     Secret in Their Eyes            3
996          Hostel: Part II            1
997   Step Up 2: The Streets            3
998             Search Party            2
999               Nine Lives            3

[1000 rows x 2 columns]

In [47]:
#handle missing values
df["Revenue (Millions)"]=df["Revenue (Millions)"].replace(
    np.nan, df["Revenue (Millions)"].mean()
)

df["Metascore"]=df["Metascore"].replace(
    np.nan, df["Metascore"].mean()
)

In [52]:
#top 5 movies
df.sort_values("Rating", ascending=False)[["Movie_Title", "Rating"]].head(5)

          Movie_Title  Rating
54    The Dark Knight     9.0
80          Inception     8.8
117            Dangal     8.8
36       Interstellar     8.6
249  The Intouchables     8.6

In [53]:
#movies with highest revenue
df.loc[df["Revenue (Millions)"].idxmax(),["Movie_Title", "Revenue (Millions)"]]

Movie_Title           Star Wars: Episode VII - The Force Awakens
Revenue (Millions)                                        936.63
Name: 50, dtype: object

In [54]:
#movies with lowest revenue
df.loc[df["Revenue (Millions)"].idxmin(),["Movie_Title", "Revenue (Millions)"]]

Movie_Title           A Kind of Murder
Revenue (Millions)                 0.0
Name: 231, dtype: object

In [55]:
#avg rating by director
df.groupby("Director")["Rating"].mean()

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

In [56]:
#movies per year
df.groupby("Year")["Movie_Title"].count()

Year
2006     44
2007     53
2008     52
2009     51
2010     60
2011     63
2012     64
2013     91
2014     98
2015    127
2016    297
Name: Movie_Title, dtype: int64

In [59]:
#movies with rating > 8 and revenue > 100
df[(df["Rating"] > 8) & (df["Revenue (Millions)"] > 100)][["Movie_Title","Rating","Revenue (Millions)"]]

                                      Movie_Title  Rating  Revenue (Millions)
0                         Guardians of the Galaxy     8.1              333.13
6                                      La La Land     8.3              151.06
36                                   Interstellar     8.6              187.99
50     Star Wars: Episode VII - The Force Awakens     8.1              936.63
54                                The Dark Knight     9.0              533.32
67                             Mad Max: Fury Road     8.1              153.63
74                                       Zootopia     8.1              341.26
76                                   The Avengers     8.1              623.28
77                           Inglourious Basterds     8.3              120.52
80                                      Inception     8.8              292.57
82                        The Wolf of Wall Street     8.2              116.87
83                                      Gone Girl     8.1              167.74
92                                       The Help     8.1              169.71
99                                   The Departed     8.5              132.37
114  Harry Potter and the Deathly Hallows: Part 2     8.1              380.96
124                         The Dark Knight Rises     8.5              448.13
138                                Shutter Island     8.1              127.97
144                              Django Unchained     8.4              162.80
241                                    Inside Out     8.2              356.45
427                          The Bourne Ultimatum     8.1              227.14
499                                            Up     8.3              292.98
634                                        WALL·E     8.4              223.81
645                                   Gran Torino     8.2              148.09
688                                   Toy Story 3     8.3              414.98
772                      How to Train Your Dragon     8.1              217.39

In [60]:
#avg rating and revenue by director
df.groupby("Director")[["Rating","Revenue (Millions)"]].mean()

                     Rating  Revenue (Millions)
Director
Aamir Khan             8.50            1.200000
Abdellatif Kechiche    7.80            2.200000
Adam Leon              6.50           82.956376
Adam McKay             7.00          109.535000
Adam Shankman          6.30           78.665000
...                     ...                 ...
Xavier Dolan           7.55           43.223188
Yimou Zhang            6.10           45.130000
Yorgos Lanthimos       7.20            4.405000
Zack Snyder            7.04          195.148000
Zackary Adler          5.10            6.530000

[644 rows x 2 columns]

In [63]:
#number of movies and avg rating by year
df.groupby("Year").agg({
    "Movie_Title":"count",
    "Rating":"mean"
})

      Movie_Title    Rating
Year
2006           44  7.125000
2007           53  7.133962
2008           52  6.784615
2009           51  6.960784
2010           60  6.826667
2011           63  6.838095
2012           64  6.925000
2013           91  6.812088
2014           98  6.837755
2015          127  6.602362
2016          297  6.436700

In [68]:
#profitability
df["Profitability"] = (df["Revenue (Millions)"] / df["Runtime (Minutes)"])

In [69]:
#top 10 profitable movies
df.sort_values("Profitability",ascending=False)[["Movie_Title","Profitability"]].head(10)

                                    Movie_Title  Profitability
50   Star Wars: Episode VII - The Force Awakens       6.886985
85                               Jurassic World       5.259516
119                                Finding Dory       5.013299
87                                       Avatar       4.694506
76                                 The Avengers       4.358601
15                      The Secret Life of Pets       4.233448
688                                 Toy Story 3       4.028932
12                                    Rogue One       4.001278
174                                      Frozen       3.928824
797                             Despicable Me 2       3.755612

In [71]:
#rating category
def rating_category(rating):
   if rating < 6:
    return "Poor"

   elif rating < 7.5:
    return "Average"

   else:
    return "Excellent"

df["Rating_Category"] = df["Rating"].apply(rating_category)
df[["Movie_Title","Rating","Rating_Category"]]

                 Movie_Title  Rating Rating_Category
0    Guardians of the Galaxy     8.1       Excellent
1                 Prometheus     7.0         Average
2                      Split     7.3         Average
3                       Sing     7.2         Average
4              Suicide Squad     6.2         Average
..                       ...     ...             ...
995     Secret in Their Eyes     6.2         Average
996          Hostel: Part II     5.5            Poor
997   Step Up 2: The Streets     6.2         Average
998             Search Party     5.6            Poor
999               Nine Lives     5.3            Poor

[1000 rows x 3 columns]